name: '[Ubuntu-20.04]Build static binary'

on: [push,pull_request]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Arrow repo
        uses: actions/checkout@v2
        with:
          path: .

      - name: Installing Build Tools.
        run: chmod +x ./configure/ubuntu-env.sh && sudo ./configure/ubuntu-env.sh

      - name: Get Arrow repo
        uses: actions/checkout@v2
        with:
          repository: apache/arrow
          ref: 'apache-arrow-1.0.0'
          path: arrow

      - name: Building Apache Arrow
        run: chmod +x ./configure/build-arrow.sh && sudo ./configure/build-arrow.sh


      - name: cmake generation
        run: mkdir parbuild && cd parbuild && cmake .. . && cd ..

      - name: SoanrCloud Installation
        run: sudo chmod +x ./configure/sonarcloud.sh && sudo ./configure/sonarcloud.sh

#      - name: make build
#        run: make -j2

      - name:  Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: parview_linux_x86_64_static_binary
          path: ./parbuild/parview
