name: Building static parquet viewer binary for linux.

on: [push,pull_request]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Get Arrow repo
        uses: actions/checkout@v2
        with:
          path: .

      - name: Installing Build Tools.
        run: chmod +x ./configure/ubuntu-env.sh && sudo ./configure/ubuntu-env.sh

      - name: Get Arrow repo
        uses: actions/checkout@v2
        with:
          repository: apache/arrow
          ref: 'apache-arrow-1.0.0'
          path: arrow

      - name: Building Apache Arrow
        run: chmod +x ./configure/build-arrow.sh && sudo ./configure/build-arrow.sh


      - name: cmake generation
        run: cmake .

      - name: make build
        run: make -j2

      - name:  Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: parview
          path: ./parview
