name: C/C++ CI

on:
  push:
    branches: [ master,release/* ]
  pull_request:
    branches: [ master,release/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run:  chmod +x ./configure/ubuntu-env.sh && sudo ./configure/ubuntu-env.sh

    - name: cmake generation
      run: cmake .

    - name: make build
      run: make
      
    - name:  Upload Artifact 
      uses: actions/upload-artifact@v2
      with: 
        path: ./parview
