name: Building static parquet viewer binary for linux.

on:
  push:
    branches: [ master,release/* ]
  pull_request:
    branches: [ master,release/* ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Installing Build Tools.
        run: chmod +x ./configure/ubuntu-env.sh && sudo ./configure/ubuntu-env.sh

      - name: Building Apache Arrow
        uses: actions/checkout@v2
        with:
          repository: apache/arrow
          path: arrow

      - name: List Values
        run: ls -ltrh


#      - name: cmake generation
#        run: cmake .
#
#      - name: make build
#        run: make
#
#      - name:  Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: parview
#          path: ./parview
