name: C/C++ CI

on:
  push:
    branches: [ master,release/* ]
  pull_request:
    branches: [ master,release/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list files
      run: ls -ltr
    - name: configure
      run:  chmod +x ./configure/ubuntu-env.sh && sudo ./configure/ubuntu-env.sh
