name: "[Macos 10.15]Building binary."

on: [push,pull_request]


jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Get Arrow repo
        uses: actions/checkout@v2
        with:
          path: .

      - name: Installing Build Tools.
        run: chmod +x ./configure/macos-env.sh &&  ./configure/macos-env.sh

      - name: Get Arrow repo
        uses: actions/checkout@v2
        with:
          repository: apache/arrow
          ref: 'apache-arrow-1.0.0'
          path: arrow

      - name: Export CPATH for Mac Compiler
        run: export CPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include

      - name: Building Apache Arrow
        run: chmod +x ./configure/build-arrow.sh && sudo ./configure/build-arrow.sh

      - name: cmake generation
        run: mkdir parbuild && cd parbuild && cmake .. . && cd ..

      - name: make build
        run: export LIBRARY_PATH=/usr/local/lib &&  make -j2 -C parbuild

      - name:  Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: parview_macos_x86_64_static_binary
          path: ./parview
