name: "[Macos 10.15]Building binary."

on: [push,pull_request]


jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Get Arrow repo
        uses: actions/checkout@v2
        with:
          path: .

      - name: Installing Build Tools.
        run: chmod +x ./configure/macos-env.sh &&  ./configure/macos-env.sh

      - name: Get Arrow repo
        uses: actions/checkout@v2
        with:
          repository: apache/arrow
          ref: 'apache-arrow-1.0.0'
          path: arrow

      - name: Building Apache Arrow
        run: chmod +x ./configure/build-arrow-mac.sh && sudo ./configure/build-arrow-mac.sh

      - name: cmake generation
        run: cmake -DCMAKE_C_COMPILER=/usr/local/bin/gcc-9 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-9 .

      - name: make build
        run: export LD_LIBRARY_PATH=/usr/local/lib && make

      - name:  Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: parview_macos_x86_64_static_binary
          path: ./parview
